### ISSUE TITLE
[v2.6.1] Snakemake TypeError: '>' not supported between instances of 'int' and 'str'

### ISSUE THREAD

**Issue by kubu4** [blobtoolkit/insdc-pipeline#14]
I've installed v2.6.1 and I've set up a clean install of the conda btk environment.

However, when I run my script (on an HPC cluster), I get the below error(s):

```
Creating specified working directory /gscratch/scrubbed/samwhite/outputs/20210625_pgen_blobtools_Panopea-generosa-v1.0/blobtoolkit.
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 40
Rules claiming more threads will be scaled down.
Provided resources: btk=1
Job counts:
	count	jobs
	1	all
	10	run_sub_pipeline
	11
Select jobs to execute...
Traceback (most recent call last):
  File "/gscratch/srlab/programs/anaconda3/envs/btk_env/lib/python3.8/site-packages/snakemake/__init__.py", line 694, in snakemake
    success = workflow.execute(
  File "/gscratch/srlab/programs/anaconda3/envs/btk_env/lib/python3.8/site-packages/snakemake/workflow.py", line 1017, in execute
    success = scheduler.schedule()
  File "/gscratch/srlab/programs/anaconda3/envs/btk_env/lib/python3.8/site-packages/snakemake/scheduler.py", line 469, in schedule
    run = self.job_selector(needrun)
  File "/gscratch/srlab/programs/anaconda3/envs/btk_env/lib/python3.8/site-packages/snakemake/scheduler.py", line 661, in job_selector_ilp
    [max(job.resources.get("_cores", 1), 1) for job in jobs]
  File "/gscratch/srlab/programs/anaconda3/envs/btk_env/lib/python3.8/site-packages/snakemake/scheduler.py", line 661, in <listcomp>
    [max(job.resources.get("_cores", 1), 1) for job in jobs]
TypeError: '>' not supported between instances of 'int' and 'str'
```

Any suggestions on what's going on? The job doesn't even begin any of the pipeline steps. 

---

Here's my `config.yaml`:

```
assembly:
  accession: draft
  file: /gscratch/scrubbed/samwhite/outputs/20210625_pgen_blobtools_Panopea-generosa-v1.0/Panopea_generosa_v1.fasta.gz
  level: scaffold
  scaffold-count: 458602
  span: 130
  prefix: Panopea_generosa_v1
busco:
  lineage_dir: /gscratch/srlab/sam/data/databases/BUSCO
  lineages:
    - archaea_odb10
    - arthropoda_odb10
    - bacteria_odb10
    - eukaryota_odb10
    - metazoa_odb10
  basal_lineages:
    - archaea_odb10
    - bacteria_odb10
    - eukaryota_odb10
reads:
  paired:
    - prefix: reads
      platform: ILLUMINA
      file: /gscratch/scrubbed/samwhite/outputs/20210625_pgen_blobtools_Panopea-generosa-v1.0/reads_1.fastq.gz;/gscratch/scrubbed/samwhite/outputs/20210625_pgen_blobtools_Panopea-generosa-v1.0/reads_2.fastq.gz
settings:
  taxdump: /gscratch/srlab/blastdbs/20210401_ncbi_taxonomy
  blast_chunk: 100000
  blast_max_chunks: 10
  blast_overlap: 0
  blast_min_length: 1000
  threads:
    blastn: 40,
    blobtools: 40,
    busco: 40,
    diamond: 40,
    diamond_blastp: 40,
    minimap: 40,
    windowmasker: 40
similarity:
  defaults:
    evalue: 1.0e-10
    max_target_seqs: 10
    import_evalue: 1.0e-25
    taxrule: buscogenes
  diamond_blastx:
    name: reference_proteomes
    path: /gscratch/srlab/blastdbs/20210401_uniprot_btk
  diamond_blastp:
    name: reference_proteomes
    path: /gscratch/srlab/blastdbs/20210401_uniprot_btk
    import_max_target_seqs: 100000
  blastn:
    name: nt
    path: /gscratch/srlab/blastdbs/20210401_ncbi_nt
taxon:
  name: Panopea generosa
  taxid: '1049056'
```

---

And, here's my script:

```shell
#!/bin/bash
## Job Name
#SBATCH --job-name=20210625_pgen_blobtools_Panopea-generosa-v1.0
## Allocation Definition
#SBATCH --account=coenv
#SBATCH --partition=coenv
## Resources
## Nodes
#SBATCH --nodes=1
## Walltime (days-hours:minutes:seconds format)
#SBATCH --time=10-00:00:00
## Memory per node
#SBATCH --mem=200G
##turn on e-mail notification
#SBATCH --mail-type=ALL
#SBATCH --mail-user=samwhite@uw.edu
## Specify the working directory for this job
#SBATCH --chdir=/gscratch/scrubbed/samwhite/outputs/20210625_pgen_blobtools_Panopea-generosa-v1.0


### Script to run the Blobtools2 Pipeline
### on trimmed 10x Genomics/HiC FastQs from 20210401.
### Using to identify sequencing contaminants in Panopea-generosa-v1.0 genome assembly
### Generates a Snakemake config file
### Outputs Blobtools2 JSON files for use in the Blobtools2 viewer

### Utilizes NCBI taxonomy dump and customized UniProt database for DIAMOND BLASTx

### Requires Anaconda to be in system $PATH!

### Follows instructions for release v2.6.0 (https://github.com/blobtoolkit/pipeline/tree/release/v2.6.0)
### And changes noted in this GitHub Issue: https://github.com/blobtoolkit/pipeline/issues/13#issuecomment-868510883

###################################################################################
# These variables need to be set by user

# Load blobtoolkit module to add btk to PATH
module load blobtoolkit-v2.6.1.module

# Set working directory
wd=$(pwd)
echo "Working directory is ${wd}."
echo ""

# Set base directory for blobltools structure
base_dir=${wd}/blobtoolkit

# Set number of CPUs to use
threads=40

# Input/output files
assembly_name=Panopea_generosa_v1
orig_fasta=/gscratch/srlab/sam/data/P_generosa/genomes/Panopea-generosa-v1.0.fa
fastq_checksums=fastq_checksums.md5
trimmed_reads_dir=/gscratch/scrubbed/samwhite/outputs/20210401_pgen_fastp_10x-genomics

## New genome name for BTK filename requirements (no periods)
genome_fasta=${wd}/Panopea_generosa_v1.fasta.gz

## BTK pipeline directory
btk_pipeline=/gscratch/srlab/programs/blobtoolkit-v2.6.1/pipeline

## Conda environment directory
conda_dir=/gscratch/srlab/programs/anaconda3/envs/btk_env


###################################################################################

# Exit script if any command fails
set -e

# Activate blobtoolkit conda environment
conda activate btk_env

# Run snakemake, btk pipeline
snakemake -p \
--use-conda \
--conda-prefix ${conda_dir} \
--directory ${base_dir} \
--configfile ${wd}/config.yaml \
--stats ${assembly_name}.blobtoolkit.stats \
-j ${threads} \
--rerun-incomplete \
-s ${btk_pipeline}/blobtoolkit.smk \
--resources btk=1
```

**Comment by rjchallis** [comment]
This is odd, it looks like it is getting a string value when looking up the number of cores somewhere. Could you try this without the threads section in your config? All the defaults are 30 or less so should be fine on your cluster.

**Comment by kubu4** [comment]
Removing thread settings in the `config.yaml` worked. The job is progressing.

Thanks!
