### ISSUE TITLE
Running pipeline locally crashes at generate_metadata - preceding steps seem erroneous

### ISSUE THREAD

**Issue by alimayy** [blobtoolkit/insdc-pipeline#6]
Hi there,

Thanks for developing this tool. Unfortunately, when I tried to run it for a local assembly, it crashed.

Before I ran the pipeline, I'd followed the steps at https://blobtoolkit.genomehubs.org/install/ and installed all the tools and the databases with the commands mentioned in that link. Next I ran the pipeline on a local Illumina paired-end-based assembly.    

The input folder structure:

```
./
├── 86121_1.fastq.gz
├── 86121_2.fastq.gz
├── 86121_config.yaml
└── 86121.fasta

```

The content of `86121_config.yaml`:

```
assembly:
  accession: draft
  level: scaffold
  scaffold-count: []
  span: []
  prefix: "86121"
busco:
  lineage_dir: /home/ali/databases/busco
  lineages: []
#- bacteria_odb10
reads:
  paired:
    - 
      - "86121"
      - ILLUMINA

settings:
  blobtools2_path: /home/ali/packages/blobtoolkit/blobtools2
  taxonomy: /home/ali/databases/taxdump
  tmp: /tmp
  blast_chunk: 100000
  blast_max_chunks: 10
  blast_overlap: 500
  chunk: 1000000

similarity:
  defaults:
    evalue: 1e-25
    max_target_seqs: 10
    root: 1
    mask_ids: 
      - 7215
  databases:
    - 
      local: /home/ali/databases/nt
      name: nt
      source: ncbi
      tool: blast
      type: nucl
    - 
      local: /home/ali/databases/uniprot
      max_target_seqs: 1
      name: reference_proteomes
      source: uniprot
      tool: diamond
      type: prot
  taxrule: bestsumorder

taxon:
  taxid: "1596"
  name: "Lactobacillus gasseri"

keep_intermediates: true

```

The snakemake command I ran:

`snakemake --snakefile Snakefile_v2 -p --use-conda --conda-prefix ~/anaconda3/envs/mambaenv/envs/snakemake/ --directory ~/projects/131938/131938/assembly_annotation/assembly_eval/86121/ --configfile ~/projects/131938/131938/assembly_annotation/assembly_eval/86121/86121_config.yaml --stats ~/projects/131938/131938/assembly_annotation/assembly_eval/86121/86121.snakemake.stats -j 32 --resources btk`

The content of `Snakefile_v2`

```
import os

"""
https://github.com/blobtoolkit/insdc-pipeline
https://blobtoolkit.genomehubs.org/pipeline/

Pipeline to run BlobTools on public assemblies
----------------------------------------------

Requirements:
 - BlobTools2 (https://github.com/blobtoolkit/blobtools2)
 - Conda (https://conda.io/docs/commands/conda-install.html)
 - SnakeMake (http://snakemake.readthedocs.io/en/stable/)

Basic usage:
  snakemake -p --use-conda \
    --directory ~/workdir \
    --configfile example.yaml \
    -j 8

© 2018-19 Richard Challis (University of Edinburgh), MIT License
© 2019-20 Richard Challis (Wellcome Sanger Institute), MIT License
"""

singularity: "docker://genomehubs/blobtoolkit:1.2"

include: 'scripts/functions.py'

supported_version = check_version()

use_singularity = check_config()

multicore = int(os.getenv('MULTICORE', 16))
maxcore = int(os.getenv('MAXCORE', 32))

similarity = apply_similarity_search_defaults()
reads = get_read_info(config)
keep = False
if 'keep_intermediates' in config:
    keep = bool(config['keep_intermediates'])
asm = config['assembly']['prefix']
rev = ''
if 'revision' in config:
    if config['revision'] > 0:
        rev = '.'+str(config['revision'])

rule all:
    """
    Dummy rule to set blobDB as target of pipeline
    """
    input:
        "%s.fasta" % asm,
        expand("%s.{sra}.bam.stats" % asm, sra=list_sra_accessions(reads)),
        expand("%s%s/{sra}_cov.json" % (asm, rev), sra=list_sra_accessions(reads)),
        expand("%s%s/{taxrule}_phylum_positions.json" % (asm, rev), taxrule=taxrule_name()),
        expand("%s.busco.{lineage}.tsv" % asm, lineage=config['busco']['lineages']),
        expand("%s%s/{lineage}_busco.json" % (asm, rev), lineage=config['busco']['lineages']),
        "%s%s/identifiers.json" % (asm, rev)


# fetch database files
#include: 'rules/fetch_ncbi_db.smk'
#include: 'rules/fetch_taxdump.smk'
#include: 'rules/fetch_uniprot.smk'
#include: 'rules/extract_uniprot.smk'
#include: 'rules/make_uniprot_db.smk'
#include: 'rules/fetch_busco_lineage.smk'
# fetch assembly files
#include: 'rules/fetch_assembly.smk'
#include: 'rules/fetch_fastq.smk'
#include: 'rules/subsample_fastq.smk'
# map reads
include: 'rules/bwa_index.smk'
include: 'rules/map_reads.smk'
include: 'rules/bamtools_stats.smk'
# make filtered databases
#include: 'rules/split_fasta.smk'
include: 'rules/make_taxid_list.smk'
include: 'rules/make_masked_lists.smk'
include: 'rules/make_diamond_db.smk'
# run similarity searches
include: 'rules/run_windowmasker.smk'
include: 'rules/chunk_fasta.smk'
include: 'rules/run_blastn.smk'
include: 'rules/extract_nohit_sequences.smk'
include: 'rules/run_diamond_blastx.smk'
include: 'rules/unchunk_blast.smk'
# run busco
include: 'rules/run_busco3.smk'
include: 'rules/run_busco4.smk'
# run blobtools
include: 'rules/generate_metadata.smk'
include: 'rules/blobtoolkit_create.smk'
include: 'rules/blobtoolkit_add_hits.smk'
include: 'rules/blobtoolkit_add_cov.smk'
include: 'rules/blobtoolkit_add_busco.smk'
```

As can be seen above, I disabled the fetch commands since I have the DBs installed and the reads and assembly are local files. In addition, I disabled the command `include: 'rules/split_fasta.smk'` because it ran for more than 2 hours without creating any split files, neither in `/tmp/reference_proteomes/` nor the database/split directory. I created an empty `reference_proteomes.done` file under `/home/ali/databases/uniprot/split` so that the pipeline continued without splitting the database. I think the pipeline just uses the non-split reference file in the following steps.

The step where it crashes is `rule generate_metadata`

```
[Mon Feb  1 01:44:33 2021]
rule generate_metadata:
    input: 86121.86121.bam.stats
    output: 86121.meta.yaml
    log: logs/86121/generate_metadata.log
    jobid: 6
    benchmark: logs/86121/generate_metadata.benchmark.txt
    wildcards: assembly=86121

python -c "import sys; print('.'.join(map(str, sys.version_info[:2])))"
Activating conda environment: /home/ali/anaconda3/envs/mambaenv/envs/snakemake/f85b7a98
python /home/ali/projects/131938/131938/assembly_annotation/assembly_eval/86121/.snakemake/scripts/tmphtg1vroi.generate_metadata.py
Activating conda environment: /home/ali/anaconda3/envs/mambaenv/envs/snakemake/f85b7a98
[Mon Feb  1 01:44:35 2021]
Error in rule generate_metadata:
    jobid: 6
    output: 86121.meta.yaml
    log: logs/86121/generate_metadata.log (check log file(s) for error message)
    conda-env: /home/ali/anaconda3/envs/mambaenv/envs/snakemake/f85b7a98

RuleException:
CalledProcessError in line 18 of /home/ali/packages/blobtoolkit/insdc-pipeline/rules/generate_metadata.smk:
Command 'source /home/ali/anaconda3/bin/activate '/home/ali/anaconda3/envs/mambaenv/envs/snakemake/f85b7a98'; set -euo pipefail;  python /home/ali/projects/131938/131938/assembly_annotation/assembly_eval/86121/.snakemake/scripts/tmphtg1vroi.generate_metadata.py' returned non-zero exit status 13.
  File "/home/ali/anaconda3/envs/mambaenv/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2265, in run_wrapper
  File "/home/ali/packages/blobtoolkit/insdc-pipeline/rules/generate_metadata.smk", line 18, in __rule_generate_metadata
  File "/home/ali/anaconda3/envs/mambaenv/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 568, in _callback
  File "/home/ali/anaconda3/envs/mambaenv/envs/snakemake/lib/python3.9/concurrent/futures/thread.py", line 52, in run
  File "/home/ali/anaconda3/envs/mambaenv/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 554, in cached_or_run
  File "/home/ali/anaconda3/envs/mambaenv/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2350, in run_wrapper
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/ali/projects/131938/131938/assembly_annotation/assembly_eval/86121/.snakemake/log/2021-02-01T014131.065720.snakemake.log

```

`generate_metadata.log`
```
2021-02-01 01:44:35,902 [INFO] line 27 Starting script: /home/ali/packages/blobtoolkit/insdc-pipeline/scripts/generate_metadata.py
2021-02-01 01:44:35,910 [ERROR] line 101 Traceback (most recent call last):
  File "/home/ali/projects/131938/131938/assembly_annotation/assembly_eval/86121/.snakemake/scripts/tmphtg1vroi.generate_metadata.py", line 80, in <module>
    accession = re.search(r'\.(.+).bam.stats', file.split(ASSEMBLY)[1]).group(1)
AttributeError: 'NoneType' object has no attribute 'group'


```

At this point the files and folders created in the working directory are:

```
./
├── 86121_1.fastq.gz
├── 86121_2.fastq.gz
├── 86121.86121.bam
├── 86121.86121.bam.stats
├── 86121.blastn.nt.root.1.minus.7215.fasta.nohit
├── 86121.blastn.nt.root.1.minus.7215.nohit
├── 86121.blastn.nt.root.1.minus.7215.out
├── 86121.blastn.nt.root.1.minus.7215.out.raw
├── 86121.chunks.fasta
├── 86121_config.yaml
├── 86121.diamond.reference_proteomes.root.1.minus.7215.out
├── 86121.fasta
├── 86121.fasta.fai
├── 86121.windowmasker.counts
├── 86121.windowmasker.fasta
├── blast
│   └── reference_proteomes.root.1.minus.7215.lists
├── logs
│   ├── 86121
│   │   ├── bamtools_stats
│   │   │   ├── 86121.benchmark.txt
│   │   │   └── 86121.log
│   │   ├── bwa_index.benchmark.txt
│   │   ├── bwa_index.log
│   │   ├── chunk_fasta.benchmark.txt
│   │   ├── chunk_fasta.log
│   │   ├── extract_nohit_sequences
│   │   │   ├── nt.root.1.minus.7215.benchmark.txt
│   │   │   └── nt.root.1.minus.7215.log
│   │   ├── generate_metadata.log
│   │   ├── map_reads
│   │   │   ├── 86121.benchmark.txt
│   │   │   └── 86121.log
│   │   ├── run_blastn
│   │   │   ├── nt.root.1.minus.7215.benchmark.txt
│   │   │   └── nt.root.1.minus.7215.log
│   │   ├── run_diamond_blastx
│   │   │   ├── reference_proteomes.root.1.minus.7215.benchmark.txt
│   │   │   └── reference_proteomes.root.1.minus.7215.log
│   │   ├── run_windowmasker.benchmark.txt
│   │   ├── run_windowmasker.log
│   │   └── unchunk_blast
│   │       ├── blastn.nt.root.1.minus.7215.benchmark.txt
│   │       └── blastn.nt.root.1.minus.7215.log
│   ├── make_diamond_db
│   │   ├── reference_proteomes.root.1.minus.7215.benchmark.txt
│   │   └── reference_proteomes.root.1.minus.7215.log
│   ├── make_masked_lists
│   │   ├── reference_proteomes.root.1.minus.7215.benchmark.txt
│   │   └── reference_proteomes.root.1.minus.7215.log
│   └── make_taxid_list
│       ├── nt.root.1.minus.7215.benchmark.txt
│       ├── nt.root.1.minus.7215.log
│       ├── reference_proteomes.root.1.minus.7215.benchmark.txt
│       └── reference_proteomes.root.1.minus.7215.log
├── nt.root.1.minus.7215.negative.taxids
├── nt.root.1.minus.7215.taxids
├── .out
├── reference_proteomes.root.1.minus.7215.dmnd
├── reference_proteomes.root.1.minus.7215.negative.taxids
├── reference_proteomes.root.1.minus.7215.taxids
└── .snakemake
    ├── auxiliary
    ├── conda-archive
    ├── incomplete
    ├── locks
    ├── log
    │   └── 2021-02-01T014131.065720.snakemake.log
    ├── metadata
    │   ├── bnQucm9vdC4xLm1pbnVzLjcyMTUubmVnYXRpdmUudGF4aWRz
    │   ├── bnQucm9vdC4xLm1pbnVzLjcyMTUudGF4aWRz
    │   ├── cmVmZXJlbmNlX3Byb3Rlb21lcy5yb290LjEubWludXMuNzIxNS50YXhpZHM=
    │   ├── cmVmZXJlbmNlX3Byb3Rlb21lcy5yb290LjEubWludXMuNzIxNS5kbW5k
    │   ├── cmVmZXJlbmNlX3Byb3Rlb21lcy5yb290LjEubWludXMuNzIxNS5uZWdhdGl2ZS50YXhpZHM=
    │   ├── ODYxMjEud2luZG93bWFza2VyLmNvdW50cw==
    │   ├── ODYxMjEud2luZG93bWFza2VyLmZhc3Rh
    │   ├── ODYxMjEuODYxMjEuYmFt
    │   ├── ODYxMjEuODYxMjEuYmFtLnN0YXRz
    │   ├── ODYxMjEuY2h1bmtzLmZhc3Rh
    │   ├── ODYxMjEuYmxhc3RuLm50LnJvb3QuMS5taW51cy43MjE1Lm5vaGl0
    │   ├── ODYxMjEuYmxhc3RuLm50LnJvb3QuMS5taW51cy43MjE1Lm91dA==
    │   ├── ODYxMjEuYmxhc3RuLm50LnJvb3QuMS5taW51cy43MjE1Lm91dC5yYXc=
    │   ├── ODYxMjEuYmxhc3RuLm50LnJvb3QuMS5taW51cy43MjE1LmZhc3RhLm5vaGl0
    │   ├── ODYxMjEuZGlhbW9uZC5yZWZlcmVuY2VfcHJvdGVvbWVzLnJvb3QuMS5taW51cy43MjE1Lm91dA==
    │   ├── ODYxMjEuZmFzdGEuc2E=
    │   ├── ODYxMjEuZmFzdGEucGFj
    │   ├── ODYxMjEuZmFzdGEuYnd0
    │   ├── ODYxMjEuZmFzdGEuYW1i
    │   ├── ODYxMjEuZmFzdGEuYW5u
    │   └── Ymxhc3QvcmVmZXJlbmNlX3Byb3Rlb21lcy5yb290LjEubWludXMuNzIxNS5saXN0cw==
    ├── scripts
    ├── shadow
    └── singularity
```

If I'm not mistaken, the reason for the crash looks like the file naming:

```
├── 86121.86121.bam
├── 86121.86121.bam.stats
```
which contain the prefix twice. In addition the file named `.out`, which seems to contain alignment results, seem to be missing the prefix (i.e. `.out` instead of `86121.out`), but I'm not sure if this is intended or not.

Is this enough information for you to reproduce the issue? Do you need any other information?

Thanks in advance

**Comment by rjchallis** [comment]
Hi thanks for including so much detail. I think you are correct that the double-prefix is causing an issue, but I think this is probably best dealt with in the file naming, other than treating it as a bug. 

The read alignment file names are formatted as `<ASSEMBLY_PREFIX>.>READFILE_PREFIX>.bam`. As you have used the same prefix for both your assembly and the read file, the assembly prefix is being repeated in the file name. When `generate_metadata` tries to parse the `.bam.stats` files, it splits the file names on the assembly prefix and takes the second part of the match as a way to remove the assembly prefix. Having the repeated prefix apparently breaks this approach.

I think that the way to handle this in the pipeline code might be to add a check when parsing the config file to make sure there are no name collisions between read and assembly files before running the pipeline.

There should be no need to comment out steps in the pipeline - if the input files already exist then those steps shouldn't run. Ideally, the pipeline would fetch and process the refseq database, with the manual install instruction being best suited to running it independently. Looking back at the install instructions I see that I didn't make that point clear at all.

The advantage to using the pipeline version (for which the `split_fasta` step should work) is that it allows the pipeline to build taxon-filtered diamond databases (excluding closely related taxa from the database in case they had contaminants in common with your sample that have been mis-assigned to the target taxon). Whether this is useful or not depends on exactly how you are running/interpreting the results. For your example, I see that you have left `mask_ids` set as in the examples (7215 = Drosophila) so I'm guessing that you aren't using this.

**Comment by alimayy** [comment]
Thanks @rjchallis for your quick and elaborate answer! I changed the file names which indeed resolved the issue. Awesome tool and visuals. Please feel free to close the ticket.

Regarding the fetch commands, in my experience they did try to download the databases even though they were present in the paths specified in the yaml file. Fortunately my organisation doesn't allow downloads via FTP, so the database files didn't get overwritten (instead the pipeline just crashed). Can it be that the pipeline tried to download database files because the filenames in the manual install (and therefore in my disk) differ from those that are checked by the pipeline? The following are the file names in the folders I specify in the .yaml file 

```
/home/ali/databases/
├── busco
│   ├── bacteria_odb10
│   ├── bacteria_odb10.2020-03-06.tar.gz
│   ├── busco_1915542749.log
│   ├── busco_836131261.log
│   └── busco_downloads
├── nt
│   ├── nt.00.nhd
│   ├── nt.00.nhi
│   ├── nt.00.nhr
│   ├── nt.00.nin
│   ├── nt.00.nnd
│   ├── nt.00.nni
│   ├── nt.00.nog
│   ├── nt.00.nsq
│   ├── nt.00.tar.gz
│   ├── nt.01.nhd
│   ├── nt.01.nhi
│   ├── nt.01.nhr
│   ├── nt.01.nin
│   ├── nt.01.nnd
│   ├── nt.01.nni
│   ├── nt.01.nog
│   ├── nt.01.nsq
│   ├── nt.01.tar.gz
│   ├── nt.02.nhd
│   ├── nt.02.nhi
│   ├── nt.02.nhr
│   ├── nt.02.nin
│   ├── nt.02.nnd
│   ├── nt.02.nni
│   ├── nt.02.nog
│   ├── nt.02.nsq
│   ├── nt.02.tar.gz
│   ├── nt.03.nhd
│   ├── nt.03.nhi
│   ├── nt.03.nhr
│   ├── nt.03.nin
│   ├── nt.03.nnd
│   ├── nt.03.nni
│   ├── nt.03.nog
│   ├── nt.03.nsq
│   ├── nt.03.tar.gz
│   ├── nt.04.nhd
│   ├── nt.04.nhi
│   ├── nt.04.nhr
│   ├── nt.04.nin
│   ├── nt.04.nnd
│   ├── nt.04.nni
│   ├── nt.04.nog
│   ├── nt.04.nsq
│   ├── nt.04.tar.gz
│   ├── nt.05.nhd
│   ├── nt.05.nhi
│   ├── nt.05.nhr
│   ├── nt.05.nin
│   ├── nt.05.nnd
│   ├── nt.05.nni
│   ├── nt.05.nog
│   ├── nt.05.nsq
│   ├── nt.05.tar.gz
│   ├── nt.06.nhd
│   ├── nt.06.nhi
│   ├── nt.06.nhr
│   ├── nt.06.nin
│   ├── nt.06.nnd
│   ├── nt.06.nni
│   ├── nt.06.nog
│   ├── nt.06.nsq
│   ├── nt.06.tar.gz
│   ├── nt.07.nhd
│   ├── nt.07.nhi
│   ├── nt.07.nhr
│   ├── nt.07.nin
│   ├── nt.07.nnd
│   ├── nt.07.nni
│   ├── nt.07.nog
│   ├── nt.07.nsq
│   ├── nt.07.tar.gz
│   ├── nt.08.nhd
│   ├── nt.08.nhi
│   ├── nt.08.nhr
│   ├── nt.08.nin
│   ├── nt.08.nnd
│   ├── nt.08.nni
│   ├── nt.08.nog
│   ├── nt.08.nsq
│   ├── nt.08.tar.gz
│   ├── nt.09.nhd
│   ├── nt.09.nhi
│   ├── nt.09.nhr
│   ├── nt.09.nin
│   ├── nt.09.nnd
│   ├── nt.09.nni
│   ├── nt.09.nog
│   ├── nt.09.nsq
│   ├── nt.09.tar.gz
│   ├── nt.10.nhd
│   ├── nt.10.nhi
│   ├── nt.10.nhr
│   ├── nt.10.nin
│   ├── nt.10.nnd
│   ├── nt.10.nni
│   ├── nt.10.nog
│   ├── nt.10.nsq
│   ├── nt.10.tar.gz
│   ├── nt.11.nhd
│   ├── nt.11.nhi
│   ├── nt.11.nhr
│   ├── nt.11.nin
│   ├── nt.11.nnd
│   ├── nt.11.nni
│   ├── nt.11.nog
│   ├── nt.11.nsq
│   ├── nt.11.tar.gz
│   ├── nt.12.nhd
│   ├── nt.12.nhi
│   ├── nt.12.nhr
│   ├── nt.12.nin
│   ├── nt.12.nnd
│   ├── nt.12.nni
│   ├── nt.12.nog
│   ├── nt.12.nsq
│   ├── nt.12.tar.gz
│   ├── nt.13.nhd
│   ├── nt.13.nhi
│   ├── nt.13.nhr
│   ├── nt.13.nin
│   ├── nt.13.nnd
│   ├── nt.13.nni
│   ├── nt.13.nog
│   ├── nt.13.nsq
│   ├── nt.13.tar.gz
│   ├── nt.14.nhd
│   ├── nt.14.nhi
│   ├── nt.14.nhr
│   ├── nt.14.nin
│   ├── nt.14.nnd
│   ├── nt.14.nni
│   ├── nt.14.nog
│   ├── nt.14.nsq
│   ├── nt.14.tar.gz
│   ├── nt.15.nhd
│   ├── nt.15.nhi
│   ├── nt.15.nhr
│   ├── nt.15.nin
│   ├── nt.15.nnd
│   ├── nt.15.nni
│   ├── nt.15.nog
│   ├── nt.15.nsq
│   ├── nt.15.tar.gz
│   ├── nt.16.nhd
│   ├── nt.16.nhi
│   ├── nt.16.nhr
│   ├── nt.16.nin
│   ├── nt.16.nnd
│   ├── nt.16.nni
│   ├── nt.16.nog
│   ├── nt.16.nsq
│   ├── nt.16.tar.gz
│   ├── nt.17.nhd
│   ├── nt.17.nhi
│   ├── nt.17.nhr
│   ├── nt.17.nin
│   ├── nt.17.nnd
│   ├── nt.17.nni
│   ├── nt.17.nog
│   ├── nt.17.nsq
│   ├── nt.17.tar.gz
│   ├── nt.18.nhd
│   ├── nt.18.nhi
│   ├── nt.18.nhr
│   ├── nt.18.nin
│   ├── nt.18.nnd
│   ├── nt.18.nni
│   ├── nt.18.nog
│   ├── nt.18.nsq
│   ├── nt.18.tar.gz
│   ├── nt.19.nhd
│   ├── nt.19.nhi
│   ├── nt.19.nhr
│   ├── nt.19.nin
│   ├── nt.19.nnd
│   ├── nt.19.nni
│   ├── nt.19.nog
│   ├── nt.19.nsq
│   ├── nt.19.tar.gz
│   ├── nt.20.nhd
│   ├── nt.20.nhi
│   ├── nt.20.nhr
│   ├── nt.20.nin
│   ├── nt.20.nnd
│   ├── nt.20.nni
│   ├── nt.20.nog
│   ├── nt.20.nsq
│   ├── nt.20.tar.gz
│   ├── nt.21.nhd
│   ├── nt.21.nhi
│   ├── nt.21.nhr
│   ├── nt.21.nin
│   ├── nt.21.nnd
│   ├── nt.21.nni
│   ├── nt.21.nog
│   ├── nt.21.nsq
│   ├── nt.21.tar.gz
│   ├── nt.22.nhd
│   ├── nt.22.nhi
│   ├── nt.22.nhr
│   ├── nt.22.nin
│   ├── nt.22.nnd
│   ├── nt.22.nni
│   ├── nt.22.nog
│   ├── nt.22.nsq
│   ├── nt.22.tar.gz
│   ├── nt.23.nhd
│   ├── nt.23.nhi
│   ├── nt.23.nhr
│   ├── nt.23.nin
│   ├── nt.23.nnd
│   ├── nt.23.nni
│   ├── nt.23.nog
│   ├── nt.23.nsq
│   ├── nt.23.tar.gz
│   ├── nt.24.nhd
│   ├── nt.24.nhi
│   ├── nt.24.nhr
│   ├── nt.24.nin
│   ├── nt.24.nnd
│   ├── nt.24.nni
│   ├── nt.24.nog
│   ├── nt.24.nsq
│   ├── nt.24.tar.gz
│   ├── nt.25.nhd
│   ├── nt.25.nhi
│   ├── nt.25.nhr
│   ├── nt.25.nin
│   ├── nt.25.nnd
│   ├── nt.25.nni
│   ├── nt.25.nog
│   ├── nt.25.nsq
│   ├── nt.25.tar.gz
│   ├── nt.26.nhd
│   ├── nt.26.nhi
│   ├── nt.26.nhr
│   ├── nt.26.nin
│   ├── nt.26.nnd
│   ├── nt.26.nni
│   ├── nt.26.nog
│   ├── nt.26.nsq
│   ├── nt.26.tar.gz
│   ├── nt.27.nhd
│   ├── nt.27.nhi
│   ├── nt.27.nhr
│   ├── nt.27.nin
│   ├── nt.27.nnd
│   ├── nt.27.nni
│   ├── nt.27.nog
│   ├── nt.27.nsq
│   ├── nt.27.tar.gz
│   ├── nt.28.nhd
│   ├── nt.28.nhi
│   ├── nt.28.nhr
│   ├── nt.28.nin
│   ├── nt.28.nnd
│   ├── nt.28.nni
│   ├── nt.28.nog
│   ├── nt.28.nsq
│   ├── nt.28.tar.gz
│   ├── nt.29.nhd
│   ├── nt.29.nhi
│   ├── nt.29.nhr
│   ├── nt.29.nin
│   ├── nt.29.nnd
│   ├── nt.29.nni
│   ├── nt.29.nog
│   ├── nt.29.nsq
│   ├── nt.29.tar.gz
│   ├── nt.30.nhd
│   ├── nt.30.nhi
│   ├── nt.30.nhr
│   ├── nt.30.nin
│   ├── nt.30.nnd
│   ├── nt.30.nni
│   ├── nt.30.nog
│   ├── nt.30.nsq
│   ├── nt.30.tar.gz
│   ├── nt.nal
│   ├── nt.ndb
│   ├── nt.nos
│   ├── nt.not
│   ├── nt.ntf
│   ├── nt.nto
│   ├── taxdb.btd
│   └── taxdb.bti
├── taxdump
│   ├── citations.dmp
│   ├── delnodes.dmp
│   ├── division.dmp
│   ├── fullnamelineage.dmp
│   ├── gencode.dmp
│   ├── host.dmp
│   ├── merged.dmp
│   ├── names.dmp
│   ├── new_taxdump.tar.gz
│   ├── nodes.dmp
│   ├── rankedlineage.dmp
│   ├── taxdump.json
│   ├── taxidlineage.dmp
│   ├── typematerial.dmp
│   └── typeoftype.dmp
├── uniprot
│   ├── Archaea
│   ├── Bacteria
│   ├── Eukaryota
│   ├── full
│   ├── README
│   ├── reference_proteomes.dmnd
│   ├── reference_proteomes.fasta.gz
│   ├── reference_proteomes.tar.gz
│   ├── reference_proteomes.taxid_map
│   ├── split
│   ├── uniprot.sh
│   └── Viruses
```

the yaml file:

```
assembly:
  accession: draft
  level: scaffold
  scaffold-count: []
  span: []
  prefix: assembly
  alias: assembly
reads:
  reads:
    Average insert size: 327
    Both pairs mapped: 5385556
    Mapped reads: 5471698
    Median insert size: 288
    Total reads: 8156812
    platform: ILLUMINA
    strategy: paired
settings:
  blobtools2_path: /home/ali/packages/blobtoolkit/blobtools2
  taxonomy: /home/ali/databases/taxdump
  tmp: /tmp
  blast_chunk: 100000
  blast_max_chunks: 10
  blast_overlap: 500
  chunk: 1000000
  commit: e2fcf93
  pipeline: https://github.com/blobtoolkit/insdc-pipeline
similarity:
  defaults:
    evalue: 1e-25
    max_target_seqs: 10
    root: 1
    mask_ids:
    - 7215
  databases:
  - local: /home/ali/databases/nt
    name: nt
    source: ncbi
    tool: blast
    type: nucl
    evalue: 1e-25
    max_target_seqs: 10
    root: 1
    mask_ids:
    - 7215
  - local: /home/ali/databases/uniprot
    max_target_seqs: 1
    name: reference_proteomes
    source: uniprot
    tool: diamond
    type: prot
    evalue: 1e-25
    root: 1
    mask_ids:
    - 7215
  taxrule: bestsumorder
taxon:
  taxid: '1596'
  name: Lactobacillus gasseri
```
